# coding: utf-8

"""
    TeamCity REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 10.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import teamcity
from teamcity.models.problem_scope import ProblemScope  # noqa: E501
from teamcity.rest import ApiException


class TestProblemScope(unittest.TestCase):
    """ProblemScope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProblemScope(self):
        """Test ProblemScope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = teamcity.models.problem_scope.ProblemScope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
