# coding: utf-8

"""
    TeamCity REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 10.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.trigger import Trigger  # noqa: E501
from swagger_client.rest import ApiException


class TestTrigger(unittest.TestCase):
    """Trigger unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTrigger(self):
        """Test Trigger"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.trigger.Trigger()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
