# coding: utf-8

"""
    TeamCity REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 10.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dohq_teamcity
from dohq_teamcity.api.vcs_root_api import VcsRootApi  # noqa: E501
from dohq_teamcity.rest import ApiException


class TestVcsRootApi(unittest.TestCase):
    """VcsRootApi unit test stubs"""

    def setUp(self):
        self.api = dohq_teamcity.api.vcs_root_api.VcsRootApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_root(self):
        """Test case for add_root

        """
        pass

    def test_change_properties(self):
        """Test case for change_properties

        """
        pass

    def test_delete_all_properties(self):
        """Test case for delete_all_properties

        """
        pass

    def test_delete_parameter(self):
        """Test case for delete_parameter

        """
        pass

    def test_delete_root(self):
        """Test case for delete_root

        """
        pass

    def test_get_settings_file(self):
        """Test case for get_settings_file

        """
        pass

    def test_put_parameter(self):
        """Test case for put_parameter

        """
        pass

    def test_serve_field(self):
        """Test case for serve_field

        """
        pass

    def test_serve_instance_field(self):
        """Test case for serve_instance_field

        """
        pass

    def test_serve_properties(self):
        """Test case for serve_properties

        """
        pass

    def test_serve_property(self):
        """Test case for serve_property

        """
        pass

    def test_serve_root(self):
        """Test case for serve_root

        """
        pass

    def test_serve_root_instance(self):
        """Test case for serve_root_instance

        """
        pass

    def test_serve_root_instance_properties(self):
        """Test case for serve_root_instance_properties

        """
        pass

    def test_serve_root_instances(self):
        """Test case for serve_root_instances

        """
        pass

    def test_serve_roots(self):
        """Test case for serve_roots

        """
        pass

    def test_set_field(self):
        """Test case for set_field

        """
        pass

    def test_set_instance_field(self):
        """Test case for set_instance_field

        """
        pass


if __name__ == '__main__':
    unittest.main()
