# coding: utf-8

"""
    TeamCity REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2018.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dohq_teamcity
from dohq_teamcity.models.build_queue_locator import BuildQueueLocator  # noqa: E501
from dohq_teamcity.rest import ApiException


class TestBuildQueueLocator(unittest.TestCase):
    """BuildQueueLocator unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBuildQueueLocator(self):
        """Test BuildQueueLocator"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dohq_teamcity.models.build_queue_locator.BuildQueueLocator()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
