# coding: utf-8

"""
    TeamCity REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 10.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.test_occurrence import TestOccurrence  # noqa: E501
from swagger_client.rest import ApiException


class TestTestOccurrence(unittest.TestCase):
    """TestOccurrence unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTestOccurrence(self):
        """Test TestOccurrence"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.test_occurrence.TestOccurrence()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
