# coding: utf-8

"""
    TeamCity REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2018.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dohq_teamcity
from dohq_teamcity.models.cloud_instance_locator import CloudInstanceLocator  # noqa: E501
from dohq_teamcity.rest import ApiException


class TestCloudInstanceLocator(unittest.TestCase):
    """CloudInstanceLocator unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCloudInstanceLocator(self):
        """Test CloudInstanceLocator"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dohq_teamcity.models.cloud_instance_locator.CloudInstanceLocator()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
