# coding: utf-8

"""
    TeamCity REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 10.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dohq_teamcity
from dohq_teamcity.api.build_queue_api import BuildQueueApi  # noqa: E501
from dohq_teamcity.rest import ApiException


class TestBuildQueueApi(unittest.TestCase):
    """BuildQueueApi unit test stubs"""

    def setUp(self):
        self.api = dohq_teamcity.api.build_queue_api.BuildQueueApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_tags(self):
        """Test case for add_tags

        """
        pass

    def test_cancel_build(self):
        """Test case for cancel_build

        """
        pass

    def test_cancel_build_0(self):
        """Test case for cancel_build_0

        """
        pass

    def test_delete_build(self):
        """Test case for delete_build

        """
        pass

    def test_delete_builds_experimental(self):
        """Test case for delete_builds_experimental

        """
        pass

    def test_get_build(self):
        """Test case for get_build

        """
        pass

    def test_get_builds(self):
        """Test case for get_builds

        """
        pass

    def test_queue_new_build(self):
        """Test case for queue_new_build

        """
        pass

    def test_replace_builds(self):
        """Test case for replace_builds

        """
        pass

    def test_replace_tags(self):
        """Test case for replace_tags

        """
        pass

    def test_serve_build_field_by_build_only(self):
        """Test case for serve_build_field_by_build_only

        """
        pass

    def test_serve_compatible_agents(self):
        """Test case for serve_compatible_agents

        """
        pass

    def test_serve_tags(self):
        """Test case for serve_tags

        """
        pass

    def test_set_build_queue_order(self):
        """Test case for set_build_queue_order

        """
        pass


if __name__ == '__main__':
    unittest.main()
