# coding: utf-8

"""
    TeamCity REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 10.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dohq_teamcity
from dohq_teamcity.models.backup_process_manager import BackupProcessManager  # noqa: E501
from dohq_teamcity.rest import ApiException


class TestBackupProcessManager(unittest.TestCase):
    """BackupProcessManager unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBackupProcessManager(self):
        """Test BackupProcessManager"""
        # FIXME: construct object with mandatory attributes with example values
        # model = teamcity.models.backup_process_manager.BackupProcessManager()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
