# coding: utf-8

"""
    TeamCity REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 10.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dohq_teamcity
from dohq_teamcity.api.build_type_api import BuildTypeApi  # noqa: E501
from dohq_teamcity.rest import ApiException


class TestBuildTypeApi(unittest.TestCase):
    """BuildTypeApi unit test stubs"""

    def setUp(self):
        self.api = dohq_teamcity.api.build_type_api.BuildTypeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_agent_requirement(self):
        """Test case for add_agent_requirement

        """
        pass

    def test_add_artifact_dep(self):
        """Test case for add_artifact_dep

        """
        pass

    def test_add_build_type(self):
        """Test case for add_build_type

        """
        pass

    def test_add_feature(self):
        """Test case for add_feature

        """
        pass

    def test_add_feature_parameter(self):
        """Test case for add_feature_parameter

        """
        pass

    def test_add_snapshot_dep(self):
        """Test case for add_snapshot_dep

        """
        pass

    def test_add_step(self):
        """Test case for add_step

        """
        pass

    def test_add_step_parameter(self):
        """Test case for add_step_parameter

        """
        pass

    def test_add_trigger(self):
        """Test case for add_trigger

        """
        pass

    def test_add_vcs_root_entry(self):
        """Test case for add_vcs_root_entry

        """
        pass

    def test_change_artifact_dep_setting(self):
        """Test case for change_artifact_dep_setting

        """
        pass

    def test_change_feature_setting(self):
        """Test case for change_feature_setting

        """
        pass

    def test_change_requirement_setting(self):
        """Test case for change_requirement_setting

        """
        pass

    def test_change_step_setting(self):
        """Test case for change_step_setting

        """
        pass

    def test_change_trigger_setting(self):
        """Test case for change_trigger_setting

        """
        pass

    def test_delete_agent_requirement(self):
        """Test case for delete_agent_requirement

        """
        pass

    def test_delete_all_parameters(self):
        """Test case for delete_all_parameters

        """
        pass

    def test_delete_all_parameters_0(self):
        """Test case for delete_all_parameters_0

        """
        pass

    def test_delete_artifact_dep(self):
        """Test case for delete_artifact_dep

        """
        pass

    def test_delete_build_type(self):
        """Test case for delete_build_type

        """
        pass

    def test_delete_feature(self):
        """Test case for delete_feature

        """
        pass

    def test_delete_parameter(self):
        """Test case for delete_parameter

        """
        pass

    def test_delete_parameter_0(self):
        """Test case for delete_parameter_0

        """
        pass

    def test_delete_snapshot_dep(self):
        """Test case for delete_snapshot_dep

        """
        pass

    def test_delete_step(self):
        """Test case for delete_step

        """
        pass

    def test_delete_template_association(self):
        """Test case for delete_template_association

        """
        pass

    def test_delete_trigger(self):
        """Test case for delete_trigger

        """
        pass

    def test_delete_vcs_root_entry(self):
        """Test case for delete_vcs_root_entry

        """
        pass

    def test_get_agent_requirement(self):
        """Test case for get_agent_requirement

        """
        pass

    def test_get_agent_requirements(self):
        """Test case for get_agent_requirements

        """
        pass

    def test_get_aliases(self):
        """Test case for get_aliases

        """
        pass

    def test_get_artifact_dep(self):
        """Test case for get_artifact_dep

        """
        pass

    def test_get_artifact_dep_setting(self):
        """Test case for get_artifact_dep_setting

        """
        pass

    def test_get_artifact_deps(self):
        """Test case for get_artifact_deps

        """
        pass

    def test_get_build_types(self):
        """Test case for get_build_types

        """
        pass

    def test_get_children(self):
        """Test case for get_children

        """
        pass

    def test_get_children_alias(self):
        """Test case for get_children_alias

        """
        pass

    def test_get_content(self):
        """Test case for get_content

        """
        pass

    def test_get_content_alias(self):
        """Test case for get_content_alias

        """
        pass

    def test_get_current_vcs_instances(self):
        """Test case for get_current_vcs_instances

        """
        pass

    def test_get_example_new_project_description(self):
        """Test case for get_example_new_project_description

        """
        pass

    def test_get_example_new_project_description_compatibility_version1(self):
        """Test case for get_example_new_project_description_compatibility_version1

        """
        pass

    def test_get_feature(self):
        """Test case for get_feature

        """
        pass

    def test_get_feature_parameter(self):
        """Test case for get_feature_parameter

        """
        pass

    def test_get_feature_parameters(self):
        """Test case for get_feature_parameters

        """
        pass

    def test_get_feature_setting(self):
        """Test case for get_feature_setting

        """
        pass

    def test_get_features(self):
        """Test case for get_features

        """
        pass

    def test_get_investigations(self):
        """Test case for get_investigations

        """
        pass

    def test_get_metadata(self):
        """Test case for get_metadata

        """
        pass

    def test_get_parameter(self):
        """Test case for get_parameter

        """
        pass

    def test_get_parameter_0(self):
        """Test case for get_parameter_0

        """
        pass

    def test_get_parameter_type(self):
        """Test case for get_parameter_type

        """
        pass

    def test_get_parameter_type_raw_value(self):
        """Test case for get_parameter_type_raw_value

        """
        pass

    def test_get_parameter_value_long(self):
        """Test case for get_parameter_value_long

        """
        pass

    def test_get_parameter_value_long_0(self):
        """Test case for get_parameter_value_long_0

        """
        pass

    def test_get_parameters(self):
        """Test case for get_parameters

        """
        pass

    def test_get_parameters_0(self):
        """Test case for get_parameters_0

        """
        pass

    def test_get_requirement_setting(self):
        """Test case for get_requirement_setting

        """
        pass

    def test_get_root(self):
        """Test case for get_root

        """
        pass

    def test_get_settings_file(self):
        """Test case for get_settings_file

        """
        pass

    def test_get_snapshot_dep(self):
        """Test case for get_snapshot_dep

        """
        pass

    def test_get_snapshot_deps(self):
        """Test case for get_snapshot_deps

        """
        pass

    def test_get_step(self):
        """Test case for get_step

        """
        pass

    def test_get_step_parameter(self):
        """Test case for get_step_parameter

        """
        pass

    def test_get_step_parameters(self):
        """Test case for get_step_parameters

        """
        pass

    def test_get_step_setting(self):
        """Test case for get_step_setting

        """
        pass

    def test_get_steps(self):
        """Test case for get_steps

        """
        pass

    def test_get_template_association(self):
        """Test case for get_template_association

        """
        pass

    def test_get_trigger(self):
        """Test case for get_trigger

        """
        pass

    def test_get_trigger_setting(self):
        """Test case for get_trigger_setting

        """
        pass

    def test_get_triggers(self):
        """Test case for get_triggers

        """
        pass

    def test_get_vcs_labeling_options(self):
        """Test case for get_vcs_labeling_options

        """
        pass

    def test_get_vcs_root_entries(self):
        """Test case for get_vcs_root_entries

        """
        pass

    def test_get_vcs_root_entry(self):
        """Test case for get_vcs_root_entry

        """
        pass

    def test_get_vcs_root_entry_checkout_rules(self):
        """Test case for get_vcs_root_entry_checkout_rules

        """
        pass

    def test_get_zipped(self):
        """Test case for get_zipped

        """
        pass

    def test_replace_agent_requirement(self):
        """Test case for replace_agent_requirement

        """
        pass

    def test_replace_agent_requirements(self):
        """Test case for replace_agent_requirements

        """
        pass

    def test_replace_artifact_dep(self):
        """Test case for replace_artifact_dep

        """
        pass

    def test_replace_artifact_deps(self):
        """Test case for replace_artifact_deps

        """
        pass

    def test_replace_feature(self):
        """Test case for replace_feature

        """
        pass

    def test_replace_feature_parameters(self):
        """Test case for replace_feature_parameters

        """
        pass

    def test_replace_features(self):
        """Test case for replace_features

        """
        pass

    def test_replace_snapshot_dep(self):
        """Test case for replace_snapshot_dep

        """
        pass

    def test_replace_snapshot_deps(self):
        """Test case for replace_snapshot_deps

        """
        pass

    def test_replace_step(self):
        """Test case for replace_step

        """
        pass

    def test_replace_step_parameters(self):
        """Test case for replace_step_parameters

        """
        pass

    def test_replace_steps(self):
        """Test case for replace_steps

        """
        pass

    def test_replace_trigger(self):
        """Test case for replace_trigger

        """
        pass

    def test_replace_triggers(self):
        """Test case for replace_triggers

        """
        pass

    def test_replace_vcs_root_entries(self):
        """Test case for replace_vcs_root_entries

        """
        pass

    def test_serve_branches(self):
        """Test case for serve_branches

        """
        pass

    def test_serve_build_field(self):
        """Test case for serve_build_field

        """
        pass

    def test_serve_build_type_builds_tags(self):
        """Test case for serve_build_type_builds_tags

        """
        pass

    def test_serve_build_type_field(self):
        """Test case for serve_build_type_field

        """
        pass

    def test_serve_build_type_template(self):
        """Test case for serve_build_type_template

        """
        pass

    def test_serve_build_type_xml(self):
        """Test case for serve_build_type_xml

        """
        pass

    def test_serve_build_with_project(self):
        """Test case for serve_build_with_project

        """
        pass

    def test_serve_builds(self):
        """Test case for serve_builds

        """
        pass

    def test_set_build_type_field(self):
        """Test case for set_build_type_field

        """
        pass

    def test_set_parameter(self):
        """Test case for set_parameter

        """
        pass

    def test_set_parameter_0(self):
        """Test case for set_parameter_0

        """
        pass

    def test_set_parameter_1(self):
        """Test case for set_parameter_1

        """
        pass

    def test_set_parameter_2(self):
        """Test case for set_parameter_2

        """
        pass

    def test_set_parameter_type(self):
        """Test case for set_parameter_type

        """
        pass

    def test_set_parameter_type_raw_value(self):
        """Test case for set_parameter_type_raw_value

        """
        pass

    def test_set_parameter_value_long(self):
        """Test case for set_parameter_value_long

        """
        pass

    def test_set_parameter_value_long_0(self):
        """Test case for set_parameter_value_long_0

        """
        pass

    def test_set_parameters(self):
        """Test case for set_parameters

        """
        pass

    def test_set_parameters_0(self):
        """Test case for set_parameters_0

        """
        pass

    def test_set_vcs_labeling_options(self):
        """Test case for set_vcs_labeling_options

        """
        pass

    def test_update_vcs_root_entry(self):
        """Test case for update_vcs_root_entry

        """
        pass

    def test_update_vcs_root_entry_checkout_rules(self):
        """Test case for update_vcs_root_entry_checkout_rules

        """
        pass


if __name__ == '__main__':
    unittest.main()
