# coding: utf-8

"""
    TeamCity REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2018.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dohq_teamcity
from dohq_teamcity.models.health_category import HealthCategory  # noqa: E501
from dohq_teamcity.rest import ApiException


class TestHealthCategory(unittest.TestCase):
    """HealthCategory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHealthCategory(self):
        """Test HealthCategory"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dohq_teamcity.models.health_category.HealthCategory()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
