# coding: utf-8

"""
    TeamCity REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 10.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dohq_teamcity
from dohq_teamcity.models.snapshot_dependencies import SnapshotDependencies  # noqa: E501
from dohq_teamcity.rest import ApiException


class TestSnapshotDependencies(unittest.TestCase):
    """SnapshotDependencies unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSnapshotDependencies(self):
        """Test SnapshotDependencies"""
        # FIXME: construct object with mandatory attributes with example values
        # model = teamcity.models.snapshot_dependencies.SnapshotDependencies()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
