# coding: utf-8

"""
    TeamCity REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 10.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import teamcity
from teamcity.api.federation_api import FederationApi  # noqa: E501
from teamcity.rest import ApiException


class TestFederationApi(unittest.TestCase):
    """FederationApi unit test stubs"""

    def setUp(self):
        self.api = teamcity.api.federation_api.FederationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_server(self):
        """Test case for add_server

        """
        pass

    def test_servers(self):
        """Test case for servers

        """
        pass


if __name__ == '__main__':
    unittest.main()
