# coding: utf-8

"""
    TeamCity REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 10.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dohq_teamcity
from dohq_teamcity.api.agent_pool_api import AgentPoolApi  # noqa: E501
from dohq_teamcity.rest import ApiException


class TestAgentPoolApi(unittest.TestCase):
    """AgentPoolApi unit test stubs"""

    def setUp(self):
        self.api = dohq_teamcity.api.agent_pool_api.AgentPoolApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_agent(self):
        """Test case for add_agent

        """
        pass

    def test_add_project(self):
        """Test case for add_project

        """
        pass

    def test_create_pool(self):
        """Test case for create_pool

        """
        pass

    def test_delete_pool(self):
        """Test case for delete_pool

        """
        pass

    def test_delete_pool_project(self):
        """Test case for delete_pool_project

        """
        pass

    def test_delete_projects(self):
        """Test case for delete_projects

        """
        pass

    def test_get_field(self):
        """Test case for get_field

        """
        pass

    def test_get_pool(self):
        """Test case for get_pool

        """
        pass

    def test_get_pool_agents(self):
        """Test case for get_pool_agents

        """
        pass

    def test_get_pool_project(self):
        """Test case for get_pool_project

        """
        pass

    def test_get_pool_projects(self):
        """Test case for get_pool_projects

        """
        pass

    def test_get_pools(self):
        """Test case for get_pools

        """
        pass

    def test_replace_projects(self):
        """Test case for replace_projects

        """
        pass

    def test_set_field(self):
        """Test case for set_field

        """
        pass


if __name__ == '__main__':
    unittest.main()
