# coding: utf-8

"""
    TeamCity REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 10.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

# TODO list
"""
Code
- teamcity.agents.get (Замена всех serve на get)
- teamcity.agents.get('id:123').pool.agents - чтобы как-то возвращался pool? С возможностью БРАТЬ по умолчанию (как заглушка в gitlab)
- Наполнение информации про agent.pool.agents
- LAZY-объекты как в https://python-gitlab.readthedocs.io/en/stable/api-usage.html

- Добавление билд-степов напрямую к конфигурации? teamcity.build_types.get(ID).steps.add()?

- Понять что за DebugAPI, DefaultApi, Server
- Retry как 502 ошибку - как сейчас в teamcity
- Рефакторинг API - аналогично, должен быть единый общий родитель? Под вопросом - нужно ли?

Docs
- Проверить что еще добавить\убрать из generate.sh
- Документация по тому что где находится, как сгенерировать документацию
- Ревью автогенерируемой документации
- Дополнение документации как в документации про python-gitlab https://python-gitlab.readthedocs.io
- Перевод документации в rst-формат

"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "dohq-teamcity"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="TeamCity REST API",
    author_email="",
    url="https://github.com/devopshq/teamcity",
    keywords=["Swagger", "TeamCity REST API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501
    """
)
