# coding: utf-8

import pprint
import re  # noqa: F401

import six


class BuildCancelRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'comment': 'str',
        'readd_into_queue': 'bool'
    }

    attribute_map = {
        'comment': 'comment',
        'readd_into_queue': 'readdIntoQueue'
    }

    def __init__(self, comment=None, readd_into_queue=False):  # noqa: E501
        """BuildCancelRequest - a model defined in Swagger"""  # noqa: E501

        self._comment = None
        self._readd_into_queue = None
        self.discriminator = None

        if comment is not None:
            self.comment = comment
        if readd_into_queue is not None:
            self.readd_into_queue = readd_into_queue

    @property
    def comment(self):
        """Gets the comment of this BuildCancelRequest.  # noqa: E501


        :return: The comment of this BuildCancelRequest.  # noqa: E501
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this BuildCancelRequest.


        :param comment: The comment of this BuildCancelRequest.  # noqa: E501
        :type: str
        """

        self._comment = comment

    @property
    def readd_into_queue(self):
        """Gets the readd_into_queue of this BuildCancelRequest.  # noqa: E501


        :return: The readd_into_queue of this BuildCancelRequest.  # noqa: E501
        :rtype: bool
        """
        return self._readd_into_queue

    @readd_into_queue.setter
    def readd_into_queue(self, readd_into_queue):
        """Sets the readd_into_queue of this BuildCancelRequest.


        :param readd_into_queue: The readd_into_queue of this BuildCancelRequest.  # noqa: E501
        :type: bool
        """

        self._readd_into_queue = readd_into_queue

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BuildCancelRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
