# coding: utf-8

import pprint
import re  # noqa: F401

import six

# from teamcity.models.investigation import Investigation  # noqa: F401,E501


class Investigations(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'count': 'int',
        'href': 'str',
        'investigation': 'list[Investigation]',
        'next_href': 'str',
        'prev_href': 'str'
    }

    attribute_map = {
        'count': 'count',
        'href': 'href',
        'investigation': 'investigation',
        'next_href': 'nextHref',
        'prev_href': 'prevHref'
    }

    def __init__(self, count=None, href=None, investigation=None, next_href=None, prev_href=None):  # noqa: E501
        """Investigations - a model defined in Swagger"""  # noqa: E501

        self._count = None
        self._href = None
        self._investigation = None
        self._next_href = None
        self._prev_href = None
        self.discriminator = None

        if count is not None:
            self.count = count
        if href is not None:
            self.href = href
        if investigation is not None:
            self.investigation = investigation
        if next_href is not None:
            self.next_href = next_href
        if prev_href is not None:
            self.prev_href = prev_href

    @property
    def count(self):
        """Gets the count of this Investigations.  # noqa: E501


        :return: The count of this Investigations.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this Investigations.


        :param count: The count of this Investigations.  # noqa: E501
        :type: int
        """

        self._count = count

    @property
    def href(self):
        """Gets the href of this Investigations.  # noqa: E501


        :return: The href of this Investigations.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this Investigations.


        :param href: The href of this Investigations.  # noqa: E501
        :type: str
        """

        self._href = href

    @property
    def investigation(self):
        """Gets the investigation of this Investigations.  # noqa: E501


        :return: The investigation of this Investigations.  # noqa: E501
        :rtype: list[Investigation]
        """
        return self._investigation

    @investigation.setter
    def investigation(self, investigation):
        """Sets the investigation of this Investigations.


        :param investigation: The investigation of this Investigations.  # noqa: E501
        :type: list[Investigation]
        """

        self._investigation = investigation

    @property
    def next_href(self):
        """Gets the next_href of this Investigations.  # noqa: E501


        :return: The next_href of this Investigations.  # noqa: E501
        :rtype: str
        """
        return self._next_href

    @next_href.setter
    def next_href(self, next_href):
        """Sets the next_href of this Investigations.


        :param next_href: The next_href of this Investigations.  # noqa: E501
        :type: str
        """

        self._next_href = next_href

    @property
    def prev_href(self):
        """Gets the prev_href of this Investigations.  # noqa: E501


        :return: The prev_href of this Investigations.  # noqa: E501
        :rtype: str
        """
        return self._prev_href

    @prev_href.setter
    def prev_href(self, prev_href):
        """Sets the prev_href of this Investigations.


        :param prev_href: The prev_href of this Investigations.  # noqa: E501
        :type: str
        """

        self._prev_href = prev_href

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Investigations):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
