# coding: utf-8

import pprint
import re  # noqa: F401

import six

# from teamcity.models.link import Link  # noqa: F401,E501


class Links(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'count': 'int',
        'link': 'list[Link]'
    }

    attribute_map = {
        'count': 'count',
        'link': 'link'
    }

    def __init__(self, count=None, link=None):  # noqa: E501
        """Links - a model defined in Swagger"""  # noqa: E501

        self._count = None
        self._link = None
        self.discriminator = None

        if count is not None:
            self.count = count
        if link is not None:
            self.link = link

    @property
    def count(self):
        """Gets the count of this Links.  # noqa: E501


        :return: The count of this Links.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this Links.


        :param count: The count of this Links.  # noqa: E501
        :type: int
        """

        self._count = count

    @property
    def link(self):
        """Gets the link of this Links.  # noqa: E501


        :return: The link of this Links.  # noqa: E501
        :rtype: list[Link]
        """
        return self._link

    @link.setter
    def link(self, link):
        """Sets the link of this Links.


        :param link: The link of this Links.  # noqa: E501
        :type: list[Link]
        """

        self._link = link

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Links):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
