# coding: utf-8

"""
    TeamCity REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 10.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

# from swagger_client.models.vcs_root_entry import VcsRootEntry  # noqa: F401,E501


class VcsRootEntries(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'count': 'int',
        'vcs_root_entry': 'list[VcsRootEntry]'
    }

    attribute_map = {
        'count': 'count',
        'vcs_root_entry': 'vcs-root-entry'
    }

    def __init__(self, count=None, vcs_root_entry=None):  # noqa: E501
        """VcsRootEntries - a model defined in Swagger"""  # noqa: E501

        self._count = None
        self._vcs_root_entry = None
        self.discriminator = None

        if count is not None:
            self.count = count
        if vcs_root_entry is not None:
            self.vcs_root_entry = vcs_root_entry

    @property
    def count(self):
        """Gets the count of this VcsRootEntries.  # noqa: E501


        :return: The count of this VcsRootEntries.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this VcsRootEntries.


        :param count: The count of this VcsRootEntries.  # noqa: E501
        :type: int
        """

        self._count = count

    @property
    def vcs_root_entry(self):
        """Gets the vcs_root_entry of this VcsRootEntries.  # noqa: E501


        :return: The vcs_root_entry of this VcsRootEntries.  # noqa: E501
        :rtype: list[VcsRootEntry]
        """
        return self._vcs_root_entry

    @vcs_root_entry.setter
    def vcs_root_entry(self, vcs_root_entry):
        """Sets the vcs_root_entry of this VcsRootEntries.


        :param vcs_root_entry: The vcs_root_entry of this VcsRootEntries.  # noqa: E501
        :type: list[VcsRootEntry]
        """

        self._vcs_root_entry = vcs_root_entry

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VcsRootEntries, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VcsRootEntries):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
