# coding: utf-8

from dohq_teamcity.custom.base_model import TeamCityObject


class ArtifactDownloadInfo(TeamCityObject):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'path': 'str',
        'download_timestamp': 'str'
    }

    attribute_map = {
        'path': 'path',
        'download_timestamp': 'downloadTimestamp'
    }

    def __init__(self, path=None, download_timestamp=None, teamcity=None):  # noqa: E501
        """ArtifactDownloadInfo - a model defined in Swagger"""  # noqa: E501

        self._path = None
        self._download_timestamp = None
        self.discriminator = None

        if path is not None:
            self.path = path
        if download_timestamp is not None:
            self.download_timestamp = download_timestamp
        super(ArtifactDownloadInfo, self).__init__(teamcity=teamcity)

    @property
    def path(self):
        """Gets the path of this ArtifactDownloadInfo.  # noqa: E501


        :return: The path of this ArtifactDownloadInfo.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this ArtifactDownloadInfo.


        :param path: The path of this ArtifactDownloadInfo.  # noqa: E501
        :type: str
        """

        self._path = path

    @property
    def download_timestamp(self):
        """Gets the download_timestamp of this ArtifactDownloadInfo.  # noqa: E501


        :return: The download_timestamp of this ArtifactDownloadInfo.  # noqa: E501
        :rtype: str
        """
        return self._download_timestamp

    @download_timestamp.setter
    def download_timestamp(self, download_timestamp):
        """Sets the download_timestamp of this ArtifactDownloadInfo.


        :param download_timestamp: The download_timestamp of this ArtifactDownloadInfo.  # noqa: E501
        :type: str
        """

        self._download_timestamp = download_timestamp
