# coding: utf-8

from dohq_teamcity.custom.base_model import TeamCityObject


# from dohq_teamcity.models.audit_event import AuditEvent  # noqa: F401,E501


class AuditEvents(TeamCityObject):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'count': 'int',
        'next_href': 'str',
        'prev_href': 'str',
        'href': 'str',
        'audit_event': 'list[AuditEvent]'
    }

    attribute_map = {
        'count': 'count',
        'next_href': 'nextHref',
        'prev_href': 'prevHref',
        'href': 'href',
        'audit_event': 'auditEvent'
    }

    def __init__(self, count=None, next_href=None, prev_href=None, href=None, audit_event=None, teamcity=None):  # noqa: E501
        """AuditEvents - a model defined in Swagger"""  # noqa: E501

        self._count = None
        self._next_href = None
        self._prev_href = None
        self._href = None
        self._audit_event = None
        self.discriminator = None

        if count is not None:
            self.count = count
        if next_href is not None:
            self.next_href = next_href
        if prev_href is not None:
            self.prev_href = prev_href
        if href is not None:
            self.href = href
        if audit_event is not None:
            self.audit_event = audit_event
        super(AuditEvents, self).__init__(teamcity=teamcity)

    @property
    def count(self):
        """Gets the count of this AuditEvents.  # noqa: E501


        :return: The count of this AuditEvents.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this AuditEvents.


        :param count: The count of this AuditEvents.  # noqa: E501
        :type: int
        """

        self._count = count

    @property
    def next_href(self):
        """Gets the next_href of this AuditEvents.  # noqa: E501


        :return: The next_href of this AuditEvents.  # noqa: E501
        :rtype: str
        """
        return self._next_href

    @next_href.setter
    def next_href(self, next_href):
        """Sets the next_href of this AuditEvents.


        :param next_href: The next_href of this AuditEvents.  # noqa: E501
        :type: str
        """

        self._next_href = next_href

    @property
    def prev_href(self):
        """Gets the prev_href of this AuditEvents.  # noqa: E501


        :return: The prev_href of this AuditEvents.  # noqa: E501
        :rtype: str
        """
        return self._prev_href

    @prev_href.setter
    def prev_href(self, prev_href):
        """Sets the prev_href of this AuditEvents.


        :param prev_href: The prev_href of this AuditEvents.  # noqa: E501
        :type: str
        """

        self._prev_href = prev_href

    @property
    def href(self):
        """Gets the href of this AuditEvents.  # noqa: E501


        :return: The href of this AuditEvents.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this AuditEvents.


        :param href: The href of this AuditEvents.  # noqa: E501
        :type: str
        """

        self._href = href

    @property
    def audit_event(self):
        """Gets the audit_event of this AuditEvents.  # noqa: E501


        :return: The audit_event of this AuditEvents.  # noqa: E501
        :rtype: list[AuditEvent]
        """
        return self._audit_event

    @audit_event.setter
    def audit_event(self, audit_event):
        """Sets the audit_event of this AuditEvents.


        :param audit_event: The audit_event of this AuditEvents.  # noqa: E501
        :type: list[AuditEvent]
        """

        self._audit_event = audit_event
