# coding: utf-8

from dohq_teamcity.custom.base_model import TeamCityObject


# from dohq_teamcity.models.properties import Properties  # noqa: F401,E501


class BuildTriggerCustomization(TeamCityObject):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'enforce_clean_checkout': 'bool',
        'enforce_clean_checkout_for_dependencies': 'bool',
        'parameters': 'Properties'
    }

    attribute_map = {
        'enforce_clean_checkout': 'enforceCleanCheckout',
        'enforce_clean_checkout_for_dependencies': 'enforceCleanCheckoutForDependencies',
        'parameters': 'parameters'
    }

    def __init__(self, enforce_clean_checkout=None, enforce_clean_checkout_for_dependencies=None, parameters=None, teamcity=None):  # noqa: E501
        """BuildTriggerCustomization - a model defined in Swagger"""  # noqa: E501

        self._enforce_clean_checkout = None
        self._enforce_clean_checkout_for_dependencies = None
        self._parameters = None
        self.discriminator = None

        if enforce_clean_checkout is not None:
            self.enforce_clean_checkout = enforce_clean_checkout
        if enforce_clean_checkout_for_dependencies is not None:
            self.enforce_clean_checkout_for_dependencies = enforce_clean_checkout_for_dependencies
        if parameters is not None:
            self.parameters = parameters
        super(BuildTriggerCustomization, self).__init__(teamcity=teamcity)

    @property
    def enforce_clean_checkout(self):
        """Gets the enforce_clean_checkout of this BuildTriggerCustomization.  # noqa: E501


        :return: The enforce_clean_checkout of this BuildTriggerCustomization.  # noqa: E501
        :rtype: bool
        """
        return self._enforce_clean_checkout

    @enforce_clean_checkout.setter
    def enforce_clean_checkout(self, enforce_clean_checkout):
        """Sets the enforce_clean_checkout of this BuildTriggerCustomization.


        :param enforce_clean_checkout: The enforce_clean_checkout of this BuildTriggerCustomization.  # noqa: E501
        :type: bool
        """

        self._enforce_clean_checkout = enforce_clean_checkout

    @property
    def enforce_clean_checkout_for_dependencies(self):
        """Gets the enforce_clean_checkout_for_dependencies of this BuildTriggerCustomization.  # noqa: E501


        :return: The enforce_clean_checkout_for_dependencies of this BuildTriggerCustomization.  # noqa: E501
        :rtype: bool
        """
        return self._enforce_clean_checkout_for_dependencies

    @enforce_clean_checkout_for_dependencies.setter
    def enforce_clean_checkout_for_dependencies(self, enforce_clean_checkout_for_dependencies):
        """Sets the enforce_clean_checkout_for_dependencies of this BuildTriggerCustomization.


        :param enforce_clean_checkout_for_dependencies: The enforce_clean_checkout_for_dependencies of this BuildTriggerCustomization.  # noqa: E501
        :type: bool
        """

        self._enforce_clean_checkout_for_dependencies = enforce_clean_checkout_for_dependencies

    @property
    def parameters(self):
        """Gets the parameters of this BuildTriggerCustomization.  # noqa: E501


        :return: The parameters of this BuildTriggerCustomization.  # noqa: E501
        :rtype: Properties
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters):
        """Sets the parameters of this BuildTriggerCustomization.


        :param parameters: The parameters of this BuildTriggerCustomization.  # noqa: E501
        :type: Properties
        """

        self._parameters = parameters
