# coding: utf-8

from dohq_teamcity.custom.base_model import TeamCityObject


# from dohq_teamcity.models.agent import Agent  # noqa: F401,E501
# from dohq_teamcity.models.agents import Agents  # noqa: F401,E501
# from dohq_teamcity.models.artifact_dependencies import ArtifactDependencies  # noqa: F401,E501
# from dohq_teamcity.models.build_triggering_options import BuildTriggeringOptions  # noqa: F401,E501
# from dohq_teamcity.models.build_type import BuildType  # noqa: F401,E501
# from dohq_teamcity.models.builds import Builds  # noqa: F401,E501
# from dohq_teamcity.models.changes import Changes  # noqa: F401,E501
# from dohq_teamcity.models.comment import Comment  # noqa: F401,E501
# from dohq_teamcity.models.datas import Datas  # noqa: F401,E501
# from dohq_teamcity.models.entries import Entries  # noqa: F401,E501
# from dohq_teamcity.models.files import Files  # noqa: F401,E501
# from dohq_teamcity.models.issues_usages import IssuesUsages  # noqa: F401,E501
# from dohq_teamcity.models.items import Items  # noqa: F401,E501
# from dohq_teamcity.models.problem_occurrences import ProblemOccurrences  # noqa: F401,E501
# from dohq_teamcity.models.progress_info import ProgressInfo  # noqa: F401,E501
# from dohq_teamcity.models.properties import Properties  # noqa: F401,E501
# from dohq_teamcity.models.revision import Revision  # noqa: F401,E501
# from dohq_teamcity.models.revisions import Revisions  # noqa: F401,E501
# from dohq_teamcity.models.tags import Tags  # noqa: F401,E501
# from dohq_teamcity.models.test_occurrences import TestOccurrences  # noqa: F401,E501
# from dohq_teamcity.models.triggered_by import TriggeredBy  # noqa: F401,E501
# from dohq_teamcity.models.user import User  # noqa: F401,E501


class Build(TeamCityObject):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'agent': 'Agent',
        'artifact_dependencies': 'Builds',
        'artifacts': 'Files',
        'attributes': 'Entries',
        'branch_name': 'str',
        'build_type': 'BuildType',
        'build_type_id': 'str',
        'build_type_internal_id': 'str',
        'canceled_info': 'Comment',
        'chain_modification_id': 'str',
        'changes': 'Changes',
        'comment': 'Comment',
        'compatible_agents': 'Agents',
        'current_settings_hash': 'str',
        'custom_artifact_dependencies': 'ArtifactDependencies',
        'default_branch': 'bool',
        'failed_to_start': 'bool',
        'finish_date': 'str',
        'history': 'bool',
        'href': 'str',
        'id': 'int',
        'last_changes': 'Changes',
        'locator': 'str',
        'metadata': 'Datas',
        'modification_id': 'str',
        'number': 'str',
        'percentage_complete': 'int',
        'personal': 'bool',
        'pin_info': 'Comment',
        'pinned': 'bool',
        'problem_occurrences': 'ProblemOccurrences',
        'properties': 'Properties',
        'queued_date': 'str',
        'related_issues': 'IssuesUsages',
        'replacement_ids': 'Items',
        'resulting_properties': 'Properties',
        'revisions': 'Revisions',
        'running': 'bool',
        'running_info': 'ProgressInfo',
        'settings_hash': 'str',
        'snapshot_dependencies': 'Builds',
        'start_date': 'str',
        'start_estimate': 'str',
        'state': 'str',
        'statistics': 'Properties',
        'status': 'str',
        'status_text': 'str',
        'tags': 'Tags',
        'task_id': 'int',
        'test_occurrences': 'TestOccurrences',
        'triggered': 'TriggeredBy',
        'triggering_options': 'BuildTriggeringOptions',
        'unspecified_branch': 'bool',
        'user': 'User',
        'versioned_settings_revision': 'Revision',
        'wait_reason': 'str',
        'web_url': 'str'
    }

    attribute_map = {
        'agent': 'agent',
        'artifact_dependencies': 'artifact-dependencies',
        'artifacts': 'artifacts',
        'attributes': 'attributes',
        'branch_name': 'branchName',
        'build_type': 'buildType',
        'build_type_id': 'buildTypeId',
        'build_type_internal_id': 'buildTypeInternalId',
        'canceled_info': 'canceledInfo',
        'chain_modification_id': 'chainModificationId',
        'changes': 'changes',
        'comment': 'comment',
        'compatible_agents': 'compatibleAgents',
        'current_settings_hash': 'currentSettingsHash',
        'custom_artifact_dependencies': 'custom-artifact-dependencies',
        'default_branch': 'defaultBranch',
        'failed_to_start': 'failedToStart',
        'finish_date': 'finishDate',
        'history': 'history',
        'href': 'href',
        'id': 'id',
        'last_changes': 'lastChanges',
        'locator': 'locator',
        'metadata': 'metadata',
        'modification_id': 'modificationId',
        'number': 'number',
        'percentage_complete': 'percentageComplete',
        'personal': 'personal',
        'pin_info': 'pinInfo',
        'pinned': 'pinned',
        'problem_occurrences': 'problemOccurrences',
        'properties': 'properties',
        'queued_date': 'queuedDate',
        'related_issues': 'relatedIssues',
        'replacement_ids': 'replacementIds',
        'resulting_properties': 'resultingProperties',
        'revisions': 'revisions',
        'running': 'running',
        'running_info': 'running-info',
        'settings_hash': 'settingsHash',
        'snapshot_dependencies': 'snapshot-dependencies',
        'start_date': 'startDate',
        'start_estimate': 'startEstimate',
        'state': 'state',
        'statistics': 'statistics',
        'status': 'status',
        'status_text': 'statusText',
        'tags': 'tags',
        'task_id': 'taskId',
        'test_occurrences': 'testOccurrences',
        'triggered': 'triggered',
        'triggering_options': 'triggeringOptions',
        'unspecified_branch': 'unspecifiedBranch',
        'user': 'user',
        'versioned_settings_revision': 'versionedSettingsRevision',
        'wait_reason': 'waitReason',
        'web_url': 'webUrl'
    }

    def __init__(self, agent=None, artifact_dependencies=None, artifacts=None, attributes=None, branch_name=None, build_type=None, build_type_id=None, build_type_internal_id=None, canceled_info=None, chain_modification_id=None, changes=None, comment=None, compatible_agents=None, current_settings_hash=None, custom_artifact_dependencies=None, default_branch=False, failed_to_start=False, finish_date=None, history=False, href=None, id=None, last_changes=None, locator=None, metadata=None, modification_id=None, number=None, percentage_complete=None, personal=False, pin_info=None, pinned=False, problem_occurrences=None, properties=None, queued_date=None, related_issues=None, replacement_ids=None, resulting_properties=None, revisions=None, running=False, running_info=None, settings_hash=None, snapshot_dependencies=None, start_date=None, start_estimate=None, state=None, statistics=None, status=None, status_text=None, tags=None, task_id=None, test_occurrences=None, triggered=None, triggering_options=None, unspecified_branch=False, user=None, versioned_settings_revision=None, wait_reason=None, web_url=None, teamcity=None):  # noqa: E501
        """Build - a model defined in Swagger"""  # noqa: E501

        self._agent = None
        self._artifact_dependencies = None
        self._artifacts = None
        self._attributes = None
        self._branch_name = None
        self._build_type = None
        self._build_type_id = None
        self._build_type_internal_id = None
        self._canceled_info = None
        self._chain_modification_id = None
        self._changes = None
        self._comment = None
        self._compatible_agents = None
        self._current_settings_hash = None
        self._custom_artifact_dependencies = None
        self._default_branch = None
        self._failed_to_start = None
        self._finish_date = None
        self._history = None
        self._href = None
        self._id = None
        self._last_changes = None
        self._locator = None
        self._metadata = None
        self._modification_id = None
        self._number = None
        self._percentage_complete = None
        self._personal = None
        self._pin_info = None
        self._pinned = None
        self._problem_occurrences = None
        self._properties = None
        self._queued_date = None
        self._related_issues = None
        self._replacement_ids = None
        self._resulting_properties = None
        self._revisions = None
        self._running = None
        self._running_info = None
        self._settings_hash = None
        self._snapshot_dependencies = None
        self._start_date = None
        self._start_estimate = None
        self._state = None
        self._statistics = None
        self._status = None
        self._status_text = None
        self._tags = None
        self._task_id = None
        self._test_occurrences = None
        self._triggered = None
        self._triggering_options = None
        self._unspecified_branch = None
        self._user = None
        self._versioned_settings_revision = None
        self._wait_reason = None
        self._web_url = None
        self.discriminator = None

        if agent is not None:
            self.agent = agent
        if artifact_dependencies is not None:
            self.artifact_dependencies = artifact_dependencies
        if artifacts is not None:
            self.artifacts = artifacts
        if attributes is not None:
            self.attributes = attributes
        if branch_name is not None:
            self.branch_name = branch_name
        if build_type is not None:
            self.build_type = build_type
        if build_type_id is not None:
            self.build_type_id = build_type_id
        if build_type_internal_id is not None:
            self.build_type_internal_id = build_type_internal_id
        if canceled_info is not None:
            self.canceled_info = canceled_info
        if chain_modification_id is not None:
            self.chain_modification_id = chain_modification_id
        if changes is not None:
            self.changes = changes
        if comment is not None:
            self.comment = comment
        if compatible_agents is not None:
            self.compatible_agents = compatible_agents
        if current_settings_hash is not None:
            self.current_settings_hash = current_settings_hash
        if custom_artifact_dependencies is not None:
            self.custom_artifact_dependencies = custom_artifact_dependencies
        if default_branch is not None:
            self.default_branch = default_branch
        if failed_to_start is not None:
            self.failed_to_start = failed_to_start
        if finish_date is not None:
            self.finish_date = finish_date
        if history is not None:
            self.history = history
        if href is not None:
            self.href = href
        if id is not None:
            self.id = id
        if last_changes is not None:
            self.last_changes = last_changes
        if locator is not None:
            self.locator = locator
        if metadata is not None:
            self.metadata = metadata
        if modification_id is not None:
            self.modification_id = modification_id
        if number is not None:
            self.number = number
        if percentage_complete is not None:
            self.percentage_complete = percentage_complete
        if personal is not None:
            self.personal = personal
        if pin_info is not None:
            self.pin_info = pin_info
        if pinned is not None:
            self.pinned = pinned
        if problem_occurrences is not None:
            self.problem_occurrences = problem_occurrences
        if properties is not None:
            self.properties = properties
        if queued_date is not None:
            self.queued_date = queued_date
        if related_issues is not None:
            self.related_issues = related_issues
        if replacement_ids is not None:
            self.replacement_ids = replacement_ids
        if resulting_properties is not None:
            self.resulting_properties = resulting_properties
        if revisions is not None:
            self.revisions = revisions
        if running is not None:
            self.running = running
        if running_info is not None:
            self.running_info = running_info
        if settings_hash is not None:
            self.settings_hash = settings_hash
        if snapshot_dependencies is not None:
            self.snapshot_dependencies = snapshot_dependencies
        if start_date is not None:
            self.start_date = start_date
        if start_estimate is not None:
            self.start_estimate = start_estimate
        if state is not None:
            self.state = state
        if statistics is not None:
            self.statistics = statistics
        if status is not None:
            self.status = status
        if status_text is not None:
            self.status_text = status_text
        if tags is not None:
            self.tags = tags
        if task_id is not None:
            self.task_id = task_id
        if test_occurrences is not None:
            self.test_occurrences = test_occurrences
        if triggered is not None:
            self.triggered = triggered
        if triggering_options is not None:
            self.triggering_options = triggering_options
        if unspecified_branch is not None:
            self.unspecified_branch = unspecified_branch
        if user is not None:
            self.user = user
        if versioned_settings_revision is not None:
            self.versioned_settings_revision = versioned_settings_revision
        if wait_reason is not None:
            self.wait_reason = wait_reason
        if web_url is not None:
            self.web_url = web_url
        super(Build, self).__init__(teamcity=teamcity)

    @property
    def agent(self):
        """Gets the agent of this Build.  # noqa: E501


        :return: The agent of this Build.  # noqa: E501
        :rtype: Agent
        """
        return self._agent

    @agent.setter
    def agent(self, agent):
        """Sets the agent of this Build.


        :param agent: The agent of this Build.  # noqa: E501
        :type: Agent
        """

        self._agent = agent

    @property
    def artifact_dependencies(self):
        """Gets the artifact_dependencies of this Build.  # noqa: E501


        :return: The artifact_dependencies of this Build.  # noqa: E501
        :rtype: Builds
        """
        return self._artifact_dependencies

    @artifact_dependencies.setter
    def artifact_dependencies(self, artifact_dependencies):
        """Sets the artifact_dependencies of this Build.


        :param artifact_dependencies: The artifact_dependencies of this Build.  # noqa: E501
        :type: Builds
        """

        self._artifact_dependencies = artifact_dependencies

    @property
    def artifacts(self):
        """Gets the artifacts of this Build.  # noqa: E501


        :return: The artifacts of this Build.  # noqa: E501
        :rtype: Files
        """
        return self._artifacts

    @artifacts.setter
    def artifacts(self, artifacts):
        """Sets the artifacts of this Build.


        :param artifacts: The artifacts of this Build.  # noqa: E501
        :type: Files
        """

        self._artifacts = artifacts

    @property
    def attributes(self):
        """Gets the attributes of this Build.  # noqa: E501


        :return: The attributes of this Build.  # noqa: E501
        :rtype: Entries
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this Build.


        :param attributes: The attributes of this Build.  # noqa: E501
        :type: Entries
        """

        self._attributes = attributes

    @property
    def branch_name(self):
        """Gets the branch_name of this Build.  # noqa: E501


        :return: The branch_name of this Build.  # noqa: E501
        :rtype: str
        """
        return self._branch_name

    @branch_name.setter
    def branch_name(self, branch_name):
        """Sets the branch_name of this Build.


        :param branch_name: The branch_name of this Build.  # noqa: E501
        :type: str
        """

        self._branch_name = branch_name

    @property
    def build_type(self):
        """Gets the build_type of this Build.  # noqa: E501


        :return: The build_type of this Build.  # noqa: E501
        :rtype: BuildType
        """
        return self._build_type

    @build_type.setter
    def build_type(self, build_type):
        """Sets the build_type of this Build.


        :param build_type: The build_type of this Build.  # noqa: E501
        :type: BuildType
        """

        self._build_type = build_type

    @property
    def build_type_id(self):
        """Gets the build_type_id of this Build.  # noqa: E501


        :return: The build_type_id of this Build.  # noqa: E501
        :rtype: str
        """
        return self._build_type_id

    @build_type_id.setter
    def build_type_id(self, build_type_id):
        """Sets the build_type_id of this Build.


        :param build_type_id: The build_type_id of this Build.  # noqa: E501
        :type: str
        """

        self._build_type_id = build_type_id

    @property
    def build_type_internal_id(self):
        """Gets the build_type_internal_id of this Build.  # noqa: E501


        :return: The build_type_internal_id of this Build.  # noqa: E501
        :rtype: str
        """
        return self._build_type_internal_id

    @build_type_internal_id.setter
    def build_type_internal_id(self, build_type_internal_id):
        """Sets the build_type_internal_id of this Build.


        :param build_type_internal_id: The build_type_internal_id of this Build.  # noqa: E501
        :type: str
        """

        self._build_type_internal_id = build_type_internal_id

    @property
    def canceled_info(self):
        """Gets the canceled_info of this Build.  # noqa: E501


        :return: The canceled_info of this Build.  # noqa: E501
        :rtype: Comment
        """
        return self._canceled_info

    @canceled_info.setter
    def canceled_info(self, canceled_info):
        """Sets the canceled_info of this Build.


        :param canceled_info: The canceled_info of this Build.  # noqa: E501
        :type: Comment
        """

        self._canceled_info = canceled_info

    @property
    def chain_modification_id(self):
        """Gets the chain_modification_id of this Build.  # noqa: E501


        :return: The chain_modification_id of this Build.  # noqa: E501
        :rtype: str
        """
        return self._chain_modification_id

    @chain_modification_id.setter
    def chain_modification_id(self, chain_modification_id):
        """Sets the chain_modification_id of this Build.


        :param chain_modification_id: The chain_modification_id of this Build.  # noqa: E501
        :type: str
        """

        self._chain_modification_id = chain_modification_id

    @property
    def changes(self):
        """Gets the changes of this Build.  # noqa: E501


        :return: The changes of this Build.  # noqa: E501
        :rtype: Changes
        """
        return self._changes

    @changes.setter
    def changes(self, changes):
        """Sets the changes of this Build.


        :param changes: The changes of this Build.  # noqa: E501
        :type: Changes
        """

        self._changes = changes

    @property
    def comment(self):
        """Gets the comment of this Build.  # noqa: E501


        :return: The comment of this Build.  # noqa: E501
        :rtype: Comment
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this Build.


        :param comment: The comment of this Build.  # noqa: E501
        :type: Comment
        """

        self._comment = comment

    @property
    def compatible_agents(self):
        """Gets the compatible_agents of this Build.  # noqa: E501


        :return: The compatible_agents of this Build.  # noqa: E501
        :rtype: Agents
        """
        return self._compatible_agents

    @compatible_agents.setter
    def compatible_agents(self, compatible_agents):
        """Sets the compatible_agents of this Build.


        :param compatible_agents: The compatible_agents of this Build.  # noqa: E501
        :type: Agents
        """

        self._compatible_agents = compatible_agents

    @property
    def current_settings_hash(self):
        """Gets the current_settings_hash of this Build.  # noqa: E501


        :return: The current_settings_hash of this Build.  # noqa: E501
        :rtype: str
        """
        return self._current_settings_hash

    @current_settings_hash.setter
    def current_settings_hash(self, current_settings_hash):
        """Sets the current_settings_hash of this Build.


        :param current_settings_hash: The current_settings_hash of this Build.  # noqa: E501
        :type: str
        """

        self._current_settings_hash = current_settings_hash

    @property
    def custom_artifact_dependencies(self):
        """Gets the custom_artifact_dependencies of this Build.  # noqa: E501


        :return: The custom_artifact_dependencies of this Build.  # noqa: E501
        :rtype: ArtifactDependencies
        """
        return self._custom_artifact_dependencies

    @custom_artifact_dependencies.setter
    def custom_artifact_dependencies(self, custom_artifact_dependencies):
        """Sets the custom_artifact_dependencies of this Build.


        :param custom_artifact_dependencies: The custom_artifact_dependencies of this Build.  # noqa: E501
        :type: ArtifactDependencies
        """

        self._custom_artifact_dependencies = custom_artifact_dependencies

    @property
    def default_branch(self):
        """Gets the default_branch of this Build.  # noqa: E501


        :return: The default_branch of this Build.  # noqa: E501
        :rtype: bool
        """
        return self._default_branch

    @default_branch.setter
    def default_branch(self, default_branch):
        """Sets the default_branch of this Build.


        :param default_branch: The default_branch of this Build.  # noqa: E501
        :type: bool
        """

        self._default_branch = default_branch

    @property
    def failed_to_start(self):
        """Gets the failed_to_start of this Build.  # noqa: E501


        :return: The failed_to_start of this Build.  # noqa: E501
        :rtype: bool
        """
        return self._failed_to_start

    @failed_to_start.setter
    def failed_to_start(self, failed_to_start):
        """Sets the failed_to_start of this Build.


        :param failed_to_start: The failed_to_start of this Build.  # noqa: E501
        :type: bool
        """

        self._failed_to_start = failed_to_start

    @property
    def finish_date(self):
        """Gets the finish_date of this Build.  # noqa: E501


        :return: The finish_date of this Build.  # noqa: E501
        :rtype: str
        """
        return self._finish_date

    @finish_date.setter
    def finish_date(self, finish_date):
        """Sets the finish_date of this Build.


        :param finish_date: The finish_date of this Build.  # noqa: E501
        :type: str
        """

        self._finish_date = finish_date

    @property
    def history(self):
        """Gets the history of this Build.  # noqa: E501


        :return: The history of this Build.  # noqa: E501
        :rtype: bool
        """
        return self._history

    @history.setter
    def history(self, history):
        """Sets the history of this Build.


        :param history: The history of this Build.  # noqa: E501
        :type: bool
        """

        self._history = history

    @property
    def href(self):
        """Gets the href of this Build.  # noqa: E501


        :return: The href of this Build.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this Build.


        :param href: The href of this Build.  # noqa: E501
        :type: str
        """

        self._href = href

    @property
    def id(self):
        """Gets the id of this Build.  # noqa: E501


        :return: The id of this Build.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Build.


        :param id: The id of this Build.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def last_changes(self):
        """Gets the last_changes of this Build.  # noqa: E501


        :return: The last_changes of this Build.  # noqa: E501
        :rtype: Changes
        """
        return self._last_changes

    @last_changes.setter
    def last_changes(self, last_changes):
        """Sets the last_changes of this Build.


        :param last_changes: The last_changes of this Build.  # noqa: E501
        :type: Changes
        """

        self._last_changes = last_changes

    @property
    def locator(self):
        """Gets the locator of this Build.  # noqa: E501


        :return: The locator of this Build.  # noqa: E501
        :rtype: str
        """
        return self._locator

    @locator.setter
    def locator(self, locator):
        """Sets the locator of this Build.


        :param locator: The locator of this Build.  # noqa: E501
        :type: str
        """

        self._locator = locator

    @property
    def metadata(self):
        """Gets the metadata of this Build.  # noqa: E501


        :return: The metadata of this Build.  # noqa: E501
        :rtype: Datas
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this Build.


        :param metadata: The metadata of this Build.  # noqa: E501
        :type: Datas
        """

        self._metadata = metadata

    @property
    def modification_id(self):
        """Gets the modification_id of this Build.  # noqa: E501


        :return: The modification_id of this Build.  # noqa: E501
        :rtype: str
        """
        return self._modification_id

    @modification_id.setter
    def modification_id(self, modification_id):
        """Sets the modification_id of this Build.


        :param modification_id: The modification_id of this Build.  # noqa: E501
        :type: str
        """

        self._modification_id = modification_id

    @property
    def number(self):
        """Gets the number of this Build.  # noqa: E501


        :return: The number of this Build.  # noqa: E501
        :rtype: str
        """
        return self._number

    @number.setter
    def number(self, number):
        """Sets the number of this Build.


        :param number: The number of this Build.  # noqa: E501
        :type: str
        """

        self._number = number

    @property
    def percentage_complete(self):
        """Gets the percentage_complete of this Build.  # noqa: E501


        :return: The percentage_complete of this Build.  # noqa: E501
        :rtype: int
        """
        return self._percentage_complete

    @percentage_complete.setter
    def percentage_complete(self, percentage_complete):
        """Sets the percentage_complete of this Build.


        :param percentage_complete: The percentage_complete of this Build.  # noqa: E501
        :type: int
        """

        self._percentage_complete = percentage_complete

    @property
    def personal(self):
        """Gets the personal of this Build.  # noqa: E501


        :return: The personal of this Build.  # noqa: E501
        :rtype: bool
        """
        return self._personal

    @personal.setter
    def personal(self, personal):
        """Sets the personal of this Build.


        :param personal: The personal of this Build.  # noqa: E501
        :type: bool
        """

        self._personal = personal

    @property
    def pin_info(self):
        """Gets the pin_info of this Build.  # noqa: E501


        :return: The pin_info of this Build.  # noqa: E501
        :rtype: Comment
        """
        return self._pin_info

    @pin_info.setter
    def pin_info(self, pin_info):
        """Sets the pin_info of this Build.


        :param pin_info: The pin_info of this Build.  # noqa: E501
        :type: Comment
        """

        self._pin_info = pin_info

    @property
    def pinned(self):
        """Gets the pinned of this Build.  # noqa: E501


        :return: The pinned of this Build.  # noqa: E501
        :rtype: bool
        """
        return self._pinned

    @pinned.setter
    def pinned(self, pinned):
        """Sets the pinned of this Build.


        :param pinned: The pinned of this Build.  # noqa: E501
        :type: bool
        """

        self._pinned = pinned

    @property
    def problem_occurrences(self):
        """Gets the problem_occurrences of this Build.  # noqa: E501


        :return: The problem_occurrences of this Build.  # noqa: E501
        :rtype: ProblemOccurrences
        """
        return self._problem_occurrences

    @problem_occurrences.setter
    def problem_occurrences(self, problem_occurrences):
        """Sets the problem_occurrences of this Build.


        :param problem_occurrences: The problem_occurrences of this Build.  # noqa: E501
        :type: ProblemOccurrences
        """

        self._problem_occurrences = problem_occurrences

    @property
    def properties(self):
        """Gets the properties of this Build.  # noqa: E501


        :return: The properties of this Build.  # noqa: E501
        :rtype: Properties
        """
        return self._properties

    @properties.setter
    def properties(self, properties):
        """Sets the properties of this Build.


        :param properties: The properties of this Build.  # noqa: E501
        :type: Properties
        """

        self._properties = properties

    @property
    def queued_date(self):
        """Gets the queued_date of this Build.  # noqa: E501


        :return: The queued_date of this Build.  # noqa: E501
        :rtype: str
        """
        return self._queued_date

    @queued_date.setter
    def queued_date(self, queued_date):
        """Sets the queued_date of this Build.


        :param queued_date: The queued_date of this Build.  # noqa: E501
        :type: str
        """

        self._queued_date = queued_date

    @property
    def related_issues(self):
        """Gets the related_issues of this Build.  # noqa: E501


        :return: The related_issues of this Build.  # noqa: E501
        :rtype: IssuesUsages
        """
        return self._related_issues

    @related_issues.setter
    def related_issues(self, related_issues):
        """Sets the related_issues of this Build.


        :param related_issues: The related_issues of this Build.  # noqa: E501
        :type: IssuesUsages
        """

        self._related_issues = related_issues

    @property
    def replacement_ids(self):
        """Gets the replacement_ids of this Build.  # noqa: E501


        :return: The replacement_ids of this Build.  # noqa: E501
        :rtype: Items
        """
        return self._replacement_ids

    @replacement_ids.setter
    def replacement_ids(self, replacement_ids):
        """Sets the replacement_ids of this Build.


        :param replacement_ids: The replacement_ids of this Build.  # noqa: E501
        :type: Items
        """

        self._replacement_ids = replacement_ids

    @property
    def resulting_properties(self):
        """Gets the resulting_properties of this Build.  # noqa: E501


        :return: The resulting_properties of this Build.  # noqa: E501
        :rtype: Properties
        """
        return self._resulting_properties

    @resulting_properties.setter
    def resulting_properties(self, resulting_properties):
        """Sets the resulting_properties of this Build.


        :param resulting_properties: The resulting_properties of this Build.  # noqa: E501
        :type: Properties
        """

        self._resulting_properties = resulting_properties

    @property
    def revisions(self):
        """Gets the revisions of this Build.  # noqa: E501


        :return: The revisions of this Build.  # noqa: E501
        :rtype: Revisions
        """
        return self._revisions

    @revisions.setter
    def revisions(self, revisions):
        """Sets the revisions of this Build.


        :param revisions: The revisions of this Build.  # noqa: E501
        :type: Revisions
        """

        self._revisions = revisions

    @property
    def running(self):
        """Gets the running of this Build.  # noqa: E501


        :return: The running of this Build.  # noqa: E501
        :rtype: bool
        """
        return self._running

    @running.setter
    def running(self, running):
        """Sets the running of this Build.


        :param running: The running of this Build.  # noqa: E501
        :type: bool
        """

        self._running = running

    @property
    def running_info(self):
        """Gets the running_info of this Build.  # noqa: E501


        :return: The running_info of this Build.  # noqa: E501
        :rtype: ProgressInfo
        """
        return self._running_info

    @running_info.setter
    def running_info(self, running_info):
        """Sets the running_info of this Build.


        :param running_info: The running_info of this Build.  # noqa: E501
        :type: ProgressInfo
        """

        self._running_info = running_info

    @property
    def settings_hash(self):
        """Gets the settings_hash of this Build.  # noqa: E501


        :return: The settings_hash of this Build.  # noqa: E501
        :rtype: str
        """
        return self._settings_hash

    @settings_hash.setter
    def settings_hash(self, settings_hash):
        """Sets the settings_hash of this Build.


        :param settings_hash: The settings_hash of this Build.  # noqa: E501
        :type: str
        """

        self._settings_hash = settings_hash

    @property
    def snapshot_dependencies(self):
        """Gets the snapshot_dependencies of this Build.  # noqa: E501


        :return: The snapshot_dependencies of this Build.  # noqa: E501
        :rtype: Builds
        """
        return self._snapshot_dependencies

    @snapshot_dependencies.setter
    def snapshot_dependencies(self, snapshot_dependencies):
        """Sets the snapshot_dependencies of this Build.


        :param snapshot_dependencies: The snapshot_dependencies of this Build.  # noqa: E501
        :type: Builds
        """

        self._snapshot_dependencies = snapshot_dependencies

    @property
    def start_date(self):
        """Gets the start_date of this Build.  # noqa: E501


        :return: The start_date of this Build.  # noqa: E501
        :rtype: str
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date):
        """Sets the start_date of this Build.


        :param start_date: The start_date of this Build.  # noqa: E501
        :type: str
        """

        self._start_date = start_date

    @property
    def start_estimate(self):
        """Gets the start_estimate of this Build.  # noqa: E501


        :return: The start_estimate of this Build.  # noqa: E501
        :rtype: str
        """
        return self._start_estimate

    @start_estimate.setter
    def start_estimate(self, start_estimate):
        """Sets the start_estimate of this Build.


        :param start_estimate: The start_estimate of this Build.  # noqa: E501
        :type: str
        """

        self._start_estimate = start_estimate

    @property
    def state(self):
        """Gets the state of this Build.  # noqa: E501


        :return: The state of this Build.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this Build.


        :param state: The state of this Build.  # noqa: E501
        :type: str
        """

        self._state = state

    @property
    def statistics(self):
        """Gets the statistics of this Build.  # noqa: E501


        :return: The statistics of this Build.  # noqa: E501
        :rtype: Properties
        """
        return self._statistics

    @statistics.setter
    def statistics(self, statistics):
        """Sets the statistics of this Build.


        :param statistics: The statistics of this Build.  # noqa: E501
        :type: Properties
        """

        self._statistics = statistics

    @property
    def status(self):
        """Gets the status of this Build.  # noqa: E501


        :return: The status of this Build.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Build.


        :param status: The status of this Build.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def status_text(self):
        """Gets the status_text of this Build.  # noqa: E501


        :return: The status_text of this Build.  # noqa: E501
        :rtype: str
        """
        return self._status_text

    @status_text.setter
    def status_text(self, status_text):
        """Sets the status_text of this Build.


        :param status_text: The status_text of this Build.  # noqa: E501
        :type: str
        """

        self._status_text = status_text

    @property
    def tags(self):
        """Gets the tags of this Build.  # noqa: E501


        :return: The tags of this Build.  # noqa: E501
        :rtype: Tags
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this Build.


        :param tags: The tags of this Build.  # noqa: E501
        :type: Tags
        """

        self._tags = tags

    @property
    def task_id(self):
        """Gets the task_id of this Build.  # noqa: E501


        :return: The task_id of this Build.  # noqa: E501
        :rtype: int
        """
        return self._task_id

    @task_id.setter
    def task_id(self, task_id):
        """Sets the task_id of this Build.


        :param task_id: The task_id of this Build.  # noqa: E501
        :type: int
        """

        self._task_id = task_id

    @property
    def test_occurrences(self):
        """Gets the test_occurrences of this Build.  # noqa: E501


        :return: The test_occurrences of this Build.  # noqa: E501
        :rtype: TestOccurrences
        """
        return self._test_occurrences

    @test_occurrences.setter
    def test_occurrences(self, test_occurrences):
        """Sets the test_occurrences of this Build.


        :param test_occurrences: The test_occurrences of this Build.  # noqa: E501
        :type: TestOccurrences
        """

        self._test_occurrences = test_occurrences

    @property
    def triggered(self):
        """Gets the triggered of this Build.  # noqa: E501


        :return: The triggered of this Build.  # noqa: E501
        :rtype: TriggeredBy
        """
        return self._triggered

    @triggered.setter
    def triggered(self, triggered):
        """Sets the triggered of this Build.


        :param triggered: The triggered of this Build.  # noqa: E501
        :type: TriggeredBy
        """

        self._triggered = triggered

    @property
    def triggering_options(self):
        """Gets the triggering_options of this Build.  # noqa: E501


        :return: The triggering_options of this Build.  # noqa: E501
        :rtype: BuildTriggeringOptions
        """
        return self._triggering_options

    @triggering_options.setter
    def triggering_options(self, triggering_options):
        """Sets the triggering_options of this Build.


        :param triggering_options: The triggering_options of this Build.  # noqa: E501
        :type: BuildTriggeringOptions
        """

        self._triggering_options = triggering_options

    @property
    def unspecified_branch(self):
        """Gets the unspecified_branch of this Build.  # noqa: E501


        :return: The unspecified_branch of this Build.  # noqa: E501
        :rtype: bool
        """
        return self._unspecified_branch

    @unspecified_branch.setter
    def unspecified_branch(self, unspecified_branch):
        """Sets the unspecified_branch of this Build.


        :param unspecified_branch: The unspecified_branch of this Build.  # noqa: E501
        :type: bool
        """

        self._unspecified_branch = unspecified_branch

    @property
    def user(self):
        """Gets the user of this Build.  # noqa: E501


        :return: The user of this Build.  # noqa: E501
        :rtype: User
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this Build.


        :param user: The user of this Build.  # noqa: E501
        :type: User
        """

        self._user = user

    @property
    def versioned_settings_revision(self):
        """Gets the versioned_settings_revision of this Build.  # noqa: E501


        :return: The versioned_settings_revision of this Build.  # noqa: E501
        :rtype: Revision
        """
        return self._versioned_settings_revision

    @versioned_settings_revision.setter
    def versioned_settings_revision(self, versioned_settings_revision):
        """Sets the versioned_settings_revision of this Build.


        :param versioned_settings_revision: The versioned_settings_revision of this Build.  # noqa: E501
        :type: Revision
        """

        self._versioned_settings_revision = versioned_settings_revision

    @property
    def wait_reason(self):
        """Gets the wait_reason of this Build.  # noqa: E501


        :return: The wait_reason of this Build.  # noqa: E501
        :rtype: str
        """
        return self._wait_reason

    @wait_reason.setter
    def wait_reason(self, wait_reason):
        """Sets the wait_reason of this Build.


        :param wait_reason: The wait_reason of this Build.  # noqa: E501
        :type: str
        """

        self._wait_reason = wait_reason

    @property
    def web_url(self):
        """Gets the web_url of this Build.  # noqa: E501


        :return: The web_url of this Build.  # noqa: E501
        :rtype: str
        """
        return self._web_url

    @web_url.setter
    def web_url(self, web_url):
        """Sets the web_url of this Build.


        :param web_url: The web_url of this Build.  # noqa: E501
        :type: str
        """

        self._web_url = web_url

