# coding: utf-8

from dohq_teamcity.custom.base_model import TeamCityObject


# from dohq_teamcity.models.cloud_instances import CloudInstances  # noqa: F401,E501
# from dohq_teamcity.models.cloud_profile import CloudProfile  # noqa: F401,E501


class CloudImage(TeamCityObject):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'href': 'str',
        'profile': 'CloudProfile',
        'instances': 'CloudInstances',
        'error_message': 'str',
        'agent_type_id': 'int',
        'agent_pool_id': 'int',
        'operating_system_name': 'str',
        'locator': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'href': 'href',
        'profile': 'profile',
        'instances': 'instances',
        'error_message': 'errorMessage',
        'agent_type_id': 'agentTypeId',
        'agent_pool_id': 'agentPoolId',
        'operating_system_name': 'operatingSystemName',
        'locator': 'locator'
    }

    def __init__(self, id=None, name=None, href=None, profile=None, instances=None, error_message=None, agent_type_id=None, agent_pool_id=None, operating_system_name=None, locator=None, teamcity=None):  # noqa: E501
        """CloudImage - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._href = None
        self._profile = None
        self._instances = None
        self._error_message = None
        self._agent_type_id = None
        self._agent_pool_id = None
        self._operating_system_name = None
        self._locator = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if href is not None:
            self.href = href
        if profile is not None:
            self.profile = profile
        if instances is not None:
            self.instances = instances
        if error_message is not None:
            self.error_message = error_message
        if agent_type_id is not None:
            self.agent_type_id = agent_type_id
        if agent_pool_id is not None:
            self.agent_pool_id = agent_pool_id
        if operating_system_name is not None:
            self.operating_system_name = operating_system_name
        if locator is not None:
            self.locator = locator
        super(CloudImage, self).__init__(teamcity=teamcity)

    @property
    def id(self):
        """Gets the id of this CloudImage.  # noqa: E501


        :return: The id of this CloudImage.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CloudImage.


        :param id: The id of this CloudImage.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this CloudImage.  # noqa: E501


        :return: The name of this CloudImage.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CloudImage.


        :param name: The name of this CloudImage.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def href(self):
        """Gets the href of this CloudImage.  # noqa: E501


        :return: The href of this CloudImage.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this CloudImage.


        :param href: The href of this CloudImage.  # noqa: E501
        :type: str
        """

        self._href = href

    @property
    def profile(self):
        """Gets the profile of this CloudImage.  # noqa: E501


        :return: The profile of this CloudImage.  # noqa: E501
        :rtype: CloudProfile
        """
        return self._profile

    @profile.setter
    def profile(self, profile):
        """Sets the profile of this CloudImage.


        :param profile: The profile of this CloudImage.  # noqa: E501
        :type: CloudProfile
        """

        self._profile = profile

    @property
    def instances(self):
        """Gets the instances of this CloudImage.  # noqa: E501


        :return: The instances of this CloudImage.  # noqa: E501
        :rtype: CloudInstances
        """
        return self._instances

    @instances.setter
    def instances(self, instances):
        """Sets the instances of this CloudImage.


        :param instances: The instances of this CloudImage.  # noqa: E501
        :type: CloudInstances
        """

        self._instances = instances

    @property
    def error_message(self):
        """Gets the error_message of this CloudImage.  # noqa: E501


        :return: The error_message of this CloudImage.  # noqa: E501
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message):
        """Sets the error_message of this CloudImage.


        :param error_message: The error_message of this CloudImage.  # noqa: E501
        :type: str
        """

        self._error_message = error_message

    @property
    def agent_type_id(self):
        """Gets the agent_type_id of this CloudImage.  # noqa: E501


        :return: The agent_type_id of this CloudImage.  # noqa: E501
        :rtype: int
        """
        return self._agent_type_id

    @agent_type_id.setter
    def agent_type_id(self, agent_type_id):
        """Sets the agent_type_id of this CloudImage.


        :param agent_type_id: The agent_type_id of this CloudImage.  # noqa: E501
        :type: int
        """

        self._agent_type_id = agent_type_id

    @property
    def agent_pool_id(self):
        """Gets the agent_pool_id of this CloudImage.  # noqa: E501


        :return: The agent_pool_id of this CloudImage.  # noqa: E501
        :rtype: int
        """
        return self._agent_pool_id

    @agent_pool_id.setter
    def agent_pool_id(self, agent_pool_id):
        """Sets the agent_pool_id of this CloudImage.


        :param agent_pool_id: The agent_pool_id of this CloudImage.  # noqa: E501
        :type: int
        """

        self._agent_pool_id = agent_pool_id

    @property
    def operating_system_name(self):
        """Gets the operating_system_name of this CloudImage.  # noqa: E501


        :return: The operating_system_name of this CloudImage.  # noqa: E501
        :rtype: str
        """
        return self._operating_system_name

    @operating_system_name.setter
    def operating_system_name(self, operating_system_name):
        """Sets the operating_system_name of this CloudImage.


        :param operating_system_name: The operating_system_name of this CloudImage.  # noqa: E501
        :type: str
        """

        self._operating_system_name = operating_system_name

    @property
    def locator(self):
        """Gets the locator of this CloudImage.  # noqa: E501


        :return: The locator of this CloudImage.  # noqa: E501
        :rtype: str
        """
        return self._locator

    @locator.setter
    def locator(self, locator):
        """Sets the locator of this CloudImage.


        :param locator: The locator of this CloudImage.  # noqa: E501
        :type: str
        """

        self._locator = locator
