# coding: utf-8

from dohq_teamcity.custom.base_model import TeamCityObject


# from dohq_teamcity.models.cloud_instance import CloudInstance  # noqa: F401,E501


class CloudInstances(TeamCityObject):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'count': 'int',
        'next_href': 'str',
        'prev_href': 'str',
        'href': 'str',
        'cloud_instance': 'list[CloudInstance]'
    }

    attribute_map = {
        'count': 'count',
        'next_href': 'nextHref',
        'prev_href': 'prevHref',
        'href': 'href',
        'cloud_instance': 'cloudInstance'
    }

    def __init__(self, count=None, next_href=None, prev_href=None, href=None, cloud_instance=None, teamcity=None):  # noqa: E501
        """CloudInstances - a model defined in Swagger"""  # noqa: E501

        self._count = None
        self._next_href = None
        self._prev_href = None
        self._href = None
        self._cloud_instance = None
        self.discriminator = None

        if count is not None:
            self.count = count
        if next_href is not None:
            self.next_href = next_href
        if prev_href is not None:
            self.prev_href = prev_href
        if href is not None:
            self.href = href
        if cloud_instance is not None:
            self.cloud_instance = cloud_instance
        super(CloudInstances, self).__init__(teamcity=teamcity)

    @property
    def count(self):
        """Gets the count of this CloudInstances.  # noqa: E501


        :return: The count of this CloudInstances.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this CloudInstances.


        :param count: The count of this CloudInstances.  # noqa: E501
        :type: int
        """

        self._count = count

    @property
    def next_href(self):
        """Gets the next_href of this CloudInstances.  # noqa: E501


        :return: The next_href of this CloudInstances.  # noqa: E501
        :rtype: str
        """
        return self._next_href

    @next_href.setter
    def next_href(self, next_href):
        """Sets the next_href of this CloudInstances.


        :param next_href: The next_href of this CloudInstances.  # noqa: E501
        :type: str
        """

        self._next_href = next_href

    @property
    def prev_href(self):
        """Gets the prev_href of this CloudInstances.  # noqa: E501


        :return: The prev_href of this CloudInstances.  # noqa: E501
        :rtype: str
        """
        return self._prev_href

    @prev_href.setter
    def prev_href(self, prev_href):
        """Sets the prev_href of this CloudInstances.


        :param prev_href: The prev_href of this CloudInstances.  # noqa: E501
        :type: str
        """

        self._prev_href = prev_href

    @property
    def href(self):
        """Gets the href of this CloudInstances.  # noqa: E501


        :return: The href of this CloudInstances.  # noqa: E501
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this CloudInstances.


        :param href: The href of this CloudInstances.  # noqa: E501
        :type: str
        """

        self._href = href

    @property
    def cloud_instance(self):
        """Gets the cloud_instance of this CloudInstances.  # noqa: E501


        :return: The cloud_instance of this CloudInstances.  # noqa: E501
        :rtype: list[CloudInstance]
        """
        return self._cloud_instance

    @cloud_instance.setter
    def cloud_instance(self, cloud_instance):
        """Sets the cloud_instance of this CloudInstances.


        :param cloud_instance: The cloud_instance of this CloudInstances.  # noqa: E501
        :type: list[CloudInstance]
        """

        self._cloud_instance = cloud_instance
