# coding: utf-8

from dohq_teamcity.custom.base_model import TeamCityObject


class Cron(TeamCityObject):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'minute': 'str',
        'hour': 'str',
        'day': 'str',
        'month': 'str',
        'day_week': 'str'
    }

    attribute_map = {
        'minute': 'minute',
        'hour': 'hour',
        'day': 'day',
        'month': 'month',
        'day_week': 'dayWeek'
    }

    def __init__(self, minute=None, hour=None, day=None, month=None, day_week=None, teamcity=None):  # noqa: E501
        """Cron - a model defined in Swagger"""  # noqa: E501

        self._minute = None
        self._hour = None
        self._day = None
        self._month = None
        self._day_week = None
        self.discriminator = None

        if minute is not None:
            self.minute = minute
        if hour is not None:
            self.hour = hour
        if day is not None:
            self.day = day
        if month is not None:
            self.month = month
        if day_week is not None:
            self.day_week = day_week
        super(Cron, self).__init__(teamcity=teamcity)

    @property
    def minute(self):
        """Gets the minute of this Cron.  # noqa: E501


        :return: The minute of this Cron.  # noqa: E501
        :rtype: str
        """
        return self._minute

    @minute.setter
    def minute(self, minute):
        """Sets the minute of this Cron.


        :param minute: The minute of this Cron.  # noqa: E501
        :type: str
        """

        self._minute = minute

    @property
    def hour(self):
        """Gets the hour of this Cron.  # noqa: E501


        :return: The hour of this Cron.  # noqa: E501
        :rtype: str
        """
        return self._hour

    @hour.setter
    def hour(self, hour):
        """Sets the hour of this Cron.


        :param hour: The hour of this Cron.  # noqa: E501
        :type: str
        """

        self._hour = hour

    @property
    def day(self):
        """Gets the day of this Cron.  # noqa: E501


        :return: The day of this Cron.  # noqa: E501
        :rtype: str
        """
        return self._day

    @day.setter
    def day(self, day):
        """Sets the day of this Cron.


        :param day: The day of this Cron.  # noqa: E501
        :type: str
        """

        self._day = day

    @property
    def month(self):
        """Gets the month of this Cron.  # noqa: E501


        :return: The month of this Cron.  # noqa: E501
        :rtype: str
        """
        return self._month

    @month.setter
    def month(self, month):
        """Sets the month of this Cron.


        :param month: The month of this Cron.  # noqa: E501
        :type: str
        """

        self._month = month

    @property
    def day_week(self):
        """Gets the day_week of this Cron.  # noqa: E501


        :return: The day_week of this Cron.  # noqa: E501
        :rtype: str
        """
        return self._day_week

    @day_week.setter
    def day_week(self, day_week):
        """Sets the day_week of this Cron.


        :param day_week: The day_week of this Cron.  # noqa: E501
        :type: str
        """

        self._day_week = day_week
