# coding: utf-8

from dohq_teamcity.custom.base_model import TeamCityObject


# from dohq_teamcity.models.responsibility import Responsibility  # noqa: F401,E501


class EnabledResponsibilities(TeamCityObject):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'count': 'int',
        'responsibility': 'list[Responsibility]'
    }

    attribute_map = {
        'count': 'count',
        'responsibility': 'responsibility'
    }

    def __init__(self, count=None, responsibility=None, teamcity=None):  # noqa: E501
        """EnabledResponsibilities - a model defined in Swagger"""  # noqa: E501

        self._count = None
        self._responsibility = None
        self.discriminator = None

        if count is not None:
            self.count = count
        if responsibility is not None:
            self.responsibility = responsibility
        super(EnabledResponsibilities, self).__init__(teamcity=teamcity)

    @property
    def count(self):
        """Gets the count of this EnabledResponsibilities.  # noqa: E501


        :return: The count of this EnabledResponsibilities.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this EnabledResponsibilities.


        :param count: The count of this EnabledResponsibilities.  # noqa: E501
        :type: int
        """

        self._count = count

    @property
    def responsibility(self):
        """Gets the responsibility of this EnabledResponsibilities.  # noqa: E501


        :return: The responsibility of this EnabledResponsibilities.  # noqa: E501
        :rtype: list[Responsibility]
        """
        return self._responsibility

    @responsibility.setter
    def responsibility(self, responsibility):
        """Sets the responsibility of this EnabledResponsibilities.


        :param responsibility: The responsibility of this EnabledResponsibilities.  # noqa: E501
        :type: list[Responsibility]
        """

        self._responsibility = responsibility
