# coding: utf-8

from dohq_teamcity.custom.base_model import TeamCityObject


# from dohq_teamcity.models.metric_tags import MetricTags  # noqa: F401,E501


class MetricValue(TeamCityObject):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'value': 'float',
        'tags': 'MetricTags'
    }

    attribute_map = {
        'name': 'name',
        'value': 'value',
        'tags': 'tags'
    }

    def __init__(self, name=None, value=None, tags=None, teamcity=None):  # noqa: E501
        """MetricValue - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._value = None
        self._tags = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if value is not None:
            self.value = value
        if tags is not None:
            self.tags = tags
        super(MetricValue, self).__init__(teamcity=teamcity)

    @property
    def name(self):
        """Gets the name of this MetricValue.  # noqa: E501


        :return: The name of this MetricValue.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this MetricValue.


        :param name: The name of this MetricValue.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def value(self):
        """Gets the value of this MetricValue.  # noqa: E501


        :return: The value of this MetricValue.  # noqa: E501
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this MetricValue.


        :param value: The value of this MetricValue.  # noqa: E501
        :type: float
        """

        self._value = value

    @property
    def tags(self):
        """Gets the tags of this MetricValue.  # noqa: E501


        :return: The tags of this MetricValue.  # noqa: E501
        :rtype: MetricTags
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this MetricValue.


        :param tags: The tags of this MetricValue.  # noqa: E501
        :type: MetricTags
        """

        self._tags = tags
