# coding: utf-8

from dohq_teamcity.custom.base_model import TeamCityObject


# from dohq_teamcity.models.related_entity import RelatedEntity  # noqa: F401,E501


class RelatedEntities(TeamCityObject):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'count': 'int',
        'entity': 'list[RelatedEntity]'
    }

    attribute_map = {
        'count': 'count',
        'entity': 'entity'
    }

    def __init__(self, count=None, entity=None, teamcity=None):  # noqa: E501
        """RelatedEntities - a model defined in Swagger"""  # noqa: E501

        self._count = None
        self._entity = None
        self.discriminator = None

        if count is not None:
            self.count = count
        if entity is not None:
            self.entity = entity
        super(RelatedEntities, self).__init__(teamcity=teamcity)

    @property
    def count(self):
        """Gets the count of this RelatedEntities.  # noqa: E501


        :return: The count of this RelatedEntities.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this RelatedEntities.


        :param count: The count of this RelatedEntities.  # noqa: E501
        :type: int
        """

        self._count = count

    @property
    def entity(self):
        """Gets the entity of this RelatedEntities.  # noqa: E501


        :return: The entity of this RelatedEntities.  # noqa: E501
        :rtype: list[RelatedEntity]
        """
        return self._entity

    @entity.setter
    def entity(self, entity):
        """Sets the entity of this RelatedEntities.


        :param entity: The entity of this RelatedEntities.  # noqa: E501
        :type: list[RelatedEntity]
        """

        self._entity = entity
