# coding: utf-8

from dohq_teamcity.custom.base_model import TeamCityObject


class TestOccurrenceLocator(TeamCityObject):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'affected_project': 'str',
        'branch': 'str',
        'build': 'str',
        'build_type': 'str',
        'count': 'int',
        'currently_failing': 'bool',
        'currently_investigated': 'bool',
        'currently_muted': 'str',
        'id': 'str',
        'ignored': 'bool',
        'include_personal': 'bool',
        'item': 'str',
        'lookup_limit': 'int',
        'muted': 'bool',
        'name': 'str',
        'new_failure': 'str',
        'start': 'int',
        'status': 'str',
        'test': 'str'
    }

    attribute_map = {
        'affected_project': 'affectedProject',
        'branch': 'branch',
        'build': 'build',
        'build_type': 'buildType',
        'count': 'count',
        'currently_failing': 'currentlyFailing',
        'currently_investigated': 'currentlyInvestigated',
        'currently_muted': 'currentlyMuted',
        'id': 'id',
        'ignored': 'ignored',
        'include_personal': 'includePersonal',
        'item': 'item',
        'lookup_limit': 'lookupLimit',
        'muted': 'muted',
        'name': 'name',
        'new_failure': 'newFailure',
        'start': 'start',
        'status': 'status',
        'test': 'test'
    }

    def __init__(self, affected_project=None, branch=None, build=None, build_type=None, count=None, currently_failing=None, currently_investigated=None, currently_muted=None, id=None, ignored=None, include_personal=None, item=None, lookup_limit=None, muted=None, name=None, new_failure=None, start=None, status=None, test=None, teamcity=None):  # noqa: E501
        """TestOccurrenceLocator - a model defined in Swagger"""  # noqa: E501

        self._affected_project = None
        self._branch = None
        self._build = None
        self._build_type = None
        self._count = None
        self._currently_failing = None
        self._currently_investigated = None
        self._currently_muted = None
        self._id = None
        self._ignored = None
        self._include_personal = None
        self._item = None
        self._lookup_limit = None
        self._muted = None
        self._name = None
        self._new_failure = None
        self._start = None
        self._status = None
        self._test = None
        self.discriminator = None

        if affected_project is not None:
            self.affected_project = affected_project
        if branch is not None:
            self.branch = branch
        if build is not None:
            self.build = build
        if build_type is not None:
            self.build_type = build_type
        if count is not None:
            self.count = count
        if currently_failing is not None:
            self.currently_failing = currently_failing
        if currently_investigated is not None:
            self.currently_investigated = currently_investigated
        if currently_muted is not None:
            self.currently_muted = currently_muted
        if id is not None:
            self.id = id
        if ignored is not None:
            self.ignored = ignored
        if include_personal is not None:
            self.include_personal = include_personal
        if item is not None:
            self.item = item
        if lookup_limit is not None:
            self.lookup_limit = lookup_limit
        if muted is not None:
            self.muted = muted
        if name is not None:
            self.name = name
        if new_failure is not None:
            self.new_failure = new_failure
        if start is not None:
            self.start = start
        if status is not None:
            self.status = status
        if test is not None:
            self.test = test
        super(TestOccurrenceLocator, self).__init__(teamcity=teamcity)

    @property
    def affected_project(self):
        """Gets the affected_project of this TestOccurrenceLocator.  # noqa: E501

        Project (direct or indirect parent) locator.  # noqa: E501

        :return: The affected_project of this TestOccurrenceLocator.  # noqa: E501
        :rtype: str
        """
        return self._affected_project

    @affected_project.setter
    def affected_project(self, affected_project):
        """Sets the affected_project of this TestOccurrenceLocator.

        Project (direct or indirect parent) locator.  # noqa: E501

        :param affected_project: The affected_project of this TestOccurrenceLocator.  # noqa: E501
        :type: str
        """

        self._affected_project = affected_project

    @property
    def branch(self):
        """Gets the branch of this TestOccurrenceLocator.  # noqa: E501


        :return: The branch of this TestOccurrenceLocator.  # noqa: E501
        :rtype: str
        """
        return self._branch

    @branch.setter
    def branch(self, branch):
        """Sets the branch of this TestOccurrenceLocator.


        :param branch: The branch of this TestOccurrenceLocator.  # noqa: E501
        :type: str
        """

        self._branch = branch

    @property
    def build(self):
        """Gets the build of this TestOccurrenceLocator.  # noqa: E501

        Build locator.  # noqa: E501

        :return: The build of this TestOccurrenceLocator.  # noqa: E501
        :rtype: str
        """
        return self._build

    @build.setter
    def build(self, build):
        """Sets the build of this TestOccurrenceLocator.

        Build locator.  # noqa: E501

        :param build: The build of this TestOccurrenceLocator.  # noqa: E501
        :type: str
        """

        self._build = build

    @property
    def build_type(self):
        """Gets the build_type of this TestOccurrenceLocator.  # noqa: E501

        Build type locator.  # noqa: E501

        :return: The build_type of this TestOccurrenceLocator.  # noqa: E501
        :rtype: str
        """
        return self._build_type

    @build_type.setter
    def build_type(self, build_type):
        """Sets the build_type of this TestOccurrenceLocator.

        Build type locator.  # noqa: E501

        :param build_type: The build_type of this TestOccurrenceLocator.  # noqa: E501
        :type: str
        """

        self._build_type = build_type

    @property
    def count(self):
        """Gets the count of this TestOccurrenceLocator.  # noqa: E501

        For paginated calls, how many entities to return per page.  # noqa: E501

        :return: The count of this TestOccurrenceLocator.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this TestOccurrenceLocator.

        For paginated calls, how many entities to return per page.  # noqa: E501

        :param count: The count of this TestOccurrenceLocator.  # noqa: E501
        :type: int
        """

        self._count = count

    @property
    def currently_failing(self):
        """Gets the currently_failing of this TestOccurrenceLocator.  # noqa: E501

        Is currently failing.  # noqa: E501

        :return: The currently_failing of this TestOccurrenceLocator.  # noqa: E501
        :rtype: bool
        """
        return self._currently_failing

    @currently_failing.setter
    def currently_failing(self, currently_failing):
        """Sets the currently_failing of this TestOccurrenceLocator.

        Is currently failing.  # noqa: E501

        :param currently_failing: The currently_failing of this TestOccurrenceLocator.  # noqa: E501
        :type: bool
        """

        self._currently_failing = currently_failing

    @property
    def currently_investigated(self):
        """Gets the currently_investigated of this TestOccurrenceLocator.  # noqa: E501

        Is currently investigated.  # noqa: E501

        :return: The currently_investigated of this TestOccurrenceLocator.  # noqa: E501
        :rtype: bool
        """
        return self._currently_investigated

    @currently_investigated.setter
    def currently_investigated(self, currently_investigated):
        """Sets the currently_investigated of this TestOccurrenceLocator.

        Is currently investigated.  # noqa: E501

        :param currently_investigated: The currently_investigated of this TestOccurrenceLocator.  # noqa: E501
        :type: bool
        """

        self._currently_investigated = currently_investigated

    @property
    def currently_muted(self):
        """Gets the currently_muted of this TestOccurrenceLocator.  # noqa: E501


        :return: The currently_muted of this TestOccurrenceLocator.  # noqa: E501
        :rtype: str
        """
        return self._currently_muted

    @currently_muted.setter
    def currently_muted(self, currently_muted):
        """Sets the currently_muted of this TestOccurrenceLocator.


        :param currently_muted: The currently_muted of this TestOccurrenceLocator.  # noqa: E501
        :type: str
        """

        self._currently_muted = currently_muted

    @property
    def id(self):
        """Gets the id of this TestOccurrenceLocator.  # noqa: E501

        Entity ID.  # noqa: E501

        :return: The id of this TestOccurrenceLocator.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TestOccurrenceLocator.

        Entity ID.  # noqa: E501

        :param id: The id of this TestOccurrenceLocator.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def ignored(self):
        """Gets the ignored of this TestOccurrenceLocator.  # noqa: E501

        Is ignored.  # noqa: E501

        :return: The ignored of this TestOccurrenceLocator.  # noqa: E501
        :rtype: bool
        """
        return self._ignored

    @ignored.setter
    def ignored(self, ignored):
        """Sets the ignored of this TestOccurrenceLocator.

        Is ignored.  # noqa: E501

        :param ignored: The ignored of this TestOccurrenceLocator.  # noqa: E501
        :type: bool
        """

        self._ignored = ignored

    @property
    def include_personal(self):
        """Gets the include_personal of this TestOccurrenceLocator.  # noqa: E501


        :return: The include_personal of this TestOccurrenceLocator.  # noqa: E501
        :rtype: bool
        """
        return self._include_personal

    @include_personal.setter
    def include_personal(self, include_personal):
        """Sets the include_personal of this TestOccurrenceLocator.


        :param include_personal: The include_personal of this TestOccurrenceLocator.  # noqa: E501
        :type: bool
        """

        self._include_personal = include_personal

    @property
    def item(self):
        """Gets the item of this TestOccurrenceLocator.  # noqa: E501

        Supply multiple locators and return a union of the results.  # noqa: E501

        :return: The item of this TestOccurrenceLocator.  # noqa: E501
        :rtype: str
        """
        return self._item

    @item.setter
    def item(self, item):
        """Sets the item of this TestOccurrenceLocator.

        Supply multiple locators and return a union of the results.  # noqa: E501

        :param item: The item of this TestOccurrenceLocator.  # noqa: E501
        :type: str
        """

        self._item = item

    @property
    def lookup_limit(self):
        """Gets the lookup_limit of this TestOccurrenceLocator.  # noqa: E501

        Limit processing to the latest `<lookupLimit>` entities.  # noqa: E501

        :return: The lookup_limit of this TestOccurrenceLocator.  # noqa: E501
        :rtype: int
        """
        return self._lookup_limit

    @lookup_limit.setter
    def lookup_limit(self, lookup_limit):
        """Sets the lookup_limit of this TestOccurrenceLocator.

        Limit processing to the latest `<lookupLimit>` entities.  # noqa: E501

        :param lookup_limit: The lookup_limit of this TestOccurrenceLocator.  # noqa: E501
        :type: int
        """

        self._lookup_limit = lookup_limit

    @property
    def muted(self):
        """Gets the muted of this TestOccurrenceLocator.  # noqa: E501

        Is muted.  # noqa: E501

        :return: The muted of this TestOccurrenceLocator.  # noqa: E501
        :rtype: bool
        """
        return self._muted

    @muted.setter
    def muted(self, muted):
        """Sets the muted of this TestOccurrenceLocator.

        Is muted.  # noqa: E501

        :param muted: The muted of this TestOccurrenceLocator.  # noqa: E501
        :type: bool
        """

        self._muted = muted

    @property
    def name(self):
        """Gets the name of this TestOccurrenceLocator.  # noqa: E501


        :return: The name of this TestOccurrenceLocator.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TestOccurrenceLocator.


        :param name: The name of this TestOccurrenceLocator.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def new_failure(self):
        """Gets the new_failure of this TestOccurrenceLocator.  # noqa: E501


        :return: The new_failure of this TestOccurrenceLocator.  # noqa: E501
        :rtype: str
        """
        return self._new_failure

    @new_failure.setter
    def new_failure(self, new_failure):
        """Sets the new_failure of this TestOccurrenceLocator.


        :param new_failure: The new_failure of this TestOccurrenceLocator.  # noqa: E501
        :type: str
        """

        self._new_failure = new_failure

    @property
    def start(self):
        """Gets the start of this TestOccurrenceLocator.  # noqa: E501

        For paginated calls, from which entity to start rendering the page.  # noqa: E501

        :return: The start of this TestOccurrenceLocator.  # noqa: E501
        :rtype: int
        """
        return self._start

    @start.setter
    def start(self, start):
        """Sets the start of this TestOccurrenceLocator.

        For paginated calls, from which entity to start rendering the page.  # noqa: E501

        :param start: The start of this TestOccurrenceLocator.  # noqa: E501
        :type: int
        """

        self._start = start

    @property
    def status(self):
        """Gets the status of this TestOccurrenceLocator.  # noqa: E501


        :return: The status of this TestOccurrenceLocator.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this TestOccurrenceLocator.


        :param status: The status of this TestOccurrenceLocator.  # noqa: E501
        :type: str
        """
        allowed_values = ["unknown", "normal", "warning", "failure", "error", "success"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def test(self):
        """Gets the test of this TestOccurrenceLocator.  # noqa: E501

        Test locator.  # noqa: E501

        :return: The test of this TestOccurrenceLocator.  # noqa: E501
        :rtype: str
        """
        return self._test

    @test.setter
    def test(self, test):
        """Sets the test of this TestOccurrenceLocator.

        Test locator.  # noqa: E501

        :param test: The test of this TestOccurrenceLocator.  # noqa: E501
        :type: str
        """

        self._test = test
