name: tests

on:
  pull_request:
    branches:
      - develop

  workflow_call:

jobs:
# TODO: https://github.com/devopshq/teamcity/issues/3 - comment carried over from .travis.yml
#   style:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.x'

#     - name: requirements
#       run: pip install -r test-requirements.txt

#     - name: run checker
#       run: flake8

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: requirements
      run: |
        pip install -r requirements.txt
        pip install -r test-requirements.txt

    - name: run tests
      run: pytest
